### ISSUE TITLE
tag validation when calling findTransactionObjectsByTag

### ISSUE THREAD

**Issue by cu-krenn** [iotaledger/iota-java#161]
Calling "findTransactionObjectsByTag" with a correct tag e.g. CONFBOX99999999999999999999 (taken from devnet) or IOTAJAVASPAM999999999999999 (taken from test) results in

`Exception in thread "main" org.iota.jota.error.ArgumentException: [Invalid tag provided.]
	at org.iota.jota.IotaAPICore.findTransactions(IotaAPICore.java:258)
	at org.iota.jota.IotaAPICore.findTransactionsByDigests(IotaAPICore.java:328)
	at org.iota.jota.IotaAPICore.findTransactionsByTags(IotaAPICore.java:340)
	at org.iota.jota.IotaAPI.findTransactionObjectsByTag(IotaAPI.java:498)
`

I think this is caused by the use of "InputValidator.isArrayOfHashes(tags)" for checking the tag as the regex checks for a length of 81 characters when a tag only has 27. Shouldn't "isValidTag" be used in this case?

I am currently using "com.github.iotaledger:iota-java:1.0.0-beta5".

Thanks
F

**Comment by kwek20** [comment]
Hello @cu-krenn 

Youre right! That must have sneaked in when i was changing all api calls with inputvalidator.
I checked the test and we are using a tx hash as test input, which is why it didnt error

For now, you can append 9's untill 81, and it should work as expected.
(Iri actually stores tags as entire 81 tryte hashes, you can see that by calling:
```
curl brord01.mainnet.iota.cafe:14265 -X POST -H 'X-IOTA-API-Version: 1.4.1' -H 'Content-Type: application/json' -d '{"command": "findTransactions", "tags": ["IOTAJAVASPAM999999999999999999999999999999999999999999999999999999999999999999999"]}'
```

**Comment by ManuZiD** [comment]
Is fixed with this PR https://github.com/iotaledger/iota-java/pull/171
